os: linux
dist: xenial
language: python

install:
  - pip install tox

script:
  - tox -r

jobs:
    include:
        - env: TOXENV=style
          python: 3.7
          dist: xenial

        - env: TOXENV=coverage
          python: 3.7
          dist: xenial

        - env: TOXENV=docs
          python: 3.7
          dist: xenial

        - env: TOXENV=py36
          python: 3.6
          
        - python: 3.7
          env: TOXENV=py37
          dist: xenial

        - env: TOXENV=py38
          python: 3.8
          dist: xenial
