language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run --source=astroalign setup.py test

after_success:
  - codecov
