language: python

python:
  - "2.7"

env:
  - TOXENV=py27
  - TOXENV=style
  - TOXENV=coverage

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - pip install --upgrade pip
  - pip install codecov

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - pip install tox

script:
  - tox -r

after_success:
  - codecov
