language: python
sudo: false
install:
  - pip install tox
script:
  - tox -r
matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=style
        - os: linux
          python: 3.6
          env: TOXENV=coverage
        
        - os: linux
          python: 3.6
          env: TOXENV=py36
        
        - os: linux
          python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
          
        - os: ox
          python: 3.6
          env: TOXENV=py36
        
        - os: osx
          python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true

after_success:
  - codecov


